apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus-slo-alert-lab
  labels:
    app: prometheus-slo-alert-lab
spec:
  replicas: 2
  selector:
    matchLabels:
      app: prometheus-slo-alert-lab
  template:
    metadata:
      labels:
        app: prometheus-slo-alert-lab
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: /metrics
        prometheus.io/port: "8000"
    spec:
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: api
          image: prometheus-slo-alert-lab:local
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop: ["ALL"]
